export default {
    "nodes": [
      { "id": "You", "group": 4 },
      { "id": "Valjean", "group": 2 },
      { "id": "Javert", "group": 2 },
      { "id": "Fantine", "group": 2 },
      { "id": "Cosette", "group": 3 },
      { "id": "Marius", "group": 3 },
      { "id": "Eponine", "group": 3 },
      { "id": "Enjolras", "group": 3 },
      { "id": "Thénardier", "group": 3 },
      { "id": "Gavroche", "group": 3 },
      { "id": "Jean", "group": 3 },
      { "id": "Alice", "group": 3 },
      { "id": "Bob", "group": 3 },
      { "id": "Eva", "group": 3 },
      { "id": "David", "group": 1 },
      { "id": "Sophie", "group": 1 },
      { "id": "Richard", "group": 1 },
      { "id": "Olivia", "group": 1 },
      { "id": "Samuel", "group": 1 },
      { "id": "Isabel", "group": 1 }
    ],
    "links": [
      { "source": "You", "target": "Valjean", "value": 1 },
      { "source": "You", "target": "Javert", "value": 1 },
      { "source": "You", "target": "Fantine", "value": 1 },
      { "source": "You", "target": "Javert", "value": 1 },
      { "source": "You", "target": "Fantine", "value": 1 },
      { "source": "You", "target": "Eva", "value": 1 },
      { "source": "You", "target": "Samuel", "value": 1 },
      { "source": "Valjean", "target": "Fantine", "value": 1 },
      { "source": "Valjean", "target": "Cosette", "value": 1 },
      { "source": "Javert", "target": "Cosette", "value": 1 },
      { "source": "Fantine", "target": "Marius", "value": 1 },
      { "source": "Cosette", "target": "Eponine", "value": 1 },
      { "source": "Marius", "target": "Enjolras", "value": 1 },
      { "source": "Marius", "target": "Thénardier", "value": 1 },
      { "source": "Marius", "target": "Valjean", "value": 1 },
      { "source": "Marius", "target": "Eponine", "value": 1 },
      { "source": "Eponine", "target": "Thénardier", "value": 1 },
      { "source": "Eponine", "target": "Gavroche", "value": 1 },
      { "source": "Enjolras", "target": "Gavroche", "value": 1 },
      { "source": "Thénardier", "target": "Alice", "value": 1 },
      { "source": "Gavroche", "target": "Bob", "value": 1 },
      { "source": "Jean", "target": "Eva", "value": 1 },
      { "source": "Alice", "target": "David", "value": 1 },
      { "source": "Bob", "target": "David", "value": 1 },
      { "source": "Eva", "target": "Sophie", "value": 1 },
      { "source": "David", "target": "Olivia", "value": 1 },
      { "source": "Sophie", "target": "Samuel", "value": 1 },
      { "source": "Richard", "target": "Isabel", "value": 1 },
      { "source": "Olivia", "target": "You", "value": 1 },
      { "source": "Samuel", "target": "You", "value": 1 },
      { "source": "Isabel", "target": "Valjean", "value": 1 },
    ]
  };